name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Завантажуємо код
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Налаштовуємо Buildx (з правильним драйвером docker-container)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container # Переконайтеся, що цей рядок присутній!
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      # 3. Логін до GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Будуємо та пушимо Docker-образ
      - name: Build and Push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/docker-production.txt
          push: true
          tags: |
            # Використовуємо фільтр '| lower' для перетворення всієї назви репозиторію на нижній регістр
            ghcr.io/${{ github.repository | lower }}/backend:latest
            ghcr.io/${{ github.repository | lower }}/backend:main
            ghcr.io/${{ github.repository | lower }}/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
