name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Завантаження коду
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Налаштування Buildx з правильним драйвером
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:buildx-stable-1
            network=host

      # 3. Логін у GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Перетворення назви репозиторію в нижній регістр
      - name: Prepare Lowercase Repository Name
        id: prepare_repo_name
        run: |
          LOWER_REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "LOWER_REPO_NAME=${LOWER_REPO_NAME}" >> $GITHUB_OUTPUT

      # 5. Збірка та пуш образу
      - name: Build and Push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/docker-production.txt
          push: true
          load: false
          tags: |
            ghcr.io/${{ steps.prepare_repo_name.outputs.LOWER_REPO_NAME }}/backend:latest
            ghcr.io/${{ steps.prepare_repo_name.outputs.LOWER_REPO_NAME }}/backend:main
            ghcr.io/${{ steps.prepare_repo_name.outputs.LOWER_REPO_NAME }}/backend:${{ github.sha }}
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
          provenance: false